# Build configuration for Buderus WPS Heat Pump Add-on
# See: https://developers.home-assistant.io/docs/add-ons/configuration#add-on-build-configuration

build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest

args:
  BUILD_ARCH: amd64

labels:
  org.opencontainers.image.title: "Buderus WPS Heat Pump"
  org.opencontainers.image.description: "Control Buderus WPS heat pumps via CAN bus over USB serial"
  org.opencontainers.image.source: "https://github.com/your-username/buderus-wps-ha"
  org.opencontainers.image.licenses: "MIT"
